-- =============================================
-- FINCA TOCA — Copia datos de public → preview
--
-- Raíz del problema: public y preview tienen las mismas
-- columnas y tipos, pero en distinto orden (public tiene gaps
-- por columnas eliminadas). SELECT * insertaría valores en
-- posiciones equivocadas → las tablas afectadas usan lista
-- explícita de columnas. A día de hoy difieren en el orden:
-- fincas_cooperativa, gastos, ingresos, recolecciones,
-- rutas_cooperativa, toros_legacy y vacas_legacy.
--
-- Cómo usar:
--   Supabase Dashboard → SQL Editor → ejecutar este script.
-- PRECAUCIÓN: borra todos los datos actuales del esquema preview.
--
-- ---------------------------------------------
-- ACTUALIZADO 2026-08-06. Cambios respecto a la versión anterior,
-- que ya NO funcionaba:
--
--  * `vacas`/`toros` se unificaron en `animales` (2026-08-04). El script
--    insertaba en `preview.vacas`/`preview.toros`, que ya no existen, y
--    no copiaba `animales`. Ahora copia `animales` y, aparte, las tablas
--    de respaldo `vacas_legacy`/`toros_legacy`.
--
--  * Multi-tenancy (2026-08-05): las 12 tablas del lado finca y `roles`
--    llevan `tenant_id`. **`preview.tenants` se vacía y se copia desde
--    `public.tenants`**: los UUID se generaron por separado en cada schema
--    y no coinciden, así que sin esto cada `tenant_id` copiado apuntaría a
--    un cliente inexistente y las filas quedarían invisibles para todos.
--    Por eso `tenants` va PRIMERO en el bloque de copia.
--
--  * `pagos_finca` no se copiaba y hoy existe en los dos schemas.
-- =============================================


-- =============================================
-- 1. DESHABILITAR FKs
--    (necesario para las dependencias circulares entre animales
--     y para insertar en cualquier orden)
-- =============================================
SET session_replication_role = 'replica';


-- =============================================
-- 2. VACIAR TABLAS PREVIEW
-- =============================================
TRUNCATE
  preview.user_itinerarios,
  preview.pagos_finca,
  preview.itinerarios_fincas,
  preview.itinerarios,
  preview.recolecciones,
  preview.rutas_fincas,
  preview.rutas_cooperativa,
  preview.fincas_cooperativa,
  preview.eventos_animal,
  preview.pajillas,
  preview.precios,
  preview.extracciones_leche,
  preview.ingresos,
  preview.pagos,
  preview.gastos,
  preview.animales,
  preview.vacas_legacy,
  preview.toros_legacy,
  preview.subconceptos_ingreso,
  preview.conceptos_ingreso,
  preview.subconceptos_gasto,
  preview.conceptos_gasto,
  preview.roles,
  preview.tenants
RESTART IDENTITY CASCADE;


-- =============================================
-- 3. COPIAR DATOS
--    Solo las GENERATED ALWAYS AS IDENTITY requieren
--    OVERRIDING SYSTEM VALUE: conceptos_gasto, conceptos_ingreso,
--    subconceptos_gasto, subconceptos_ingreso y pagos. El resto
--    son BY DEFAULT (o serial, en pagos_finca) y aceptan el id
--    explícito sin más.
--    Tablas con columnas en distinto orden entre
--    public y preview usan lista explícita.
-- =============================================

-- Clientes — PRIMERO: todo lo demás referencia estos UUID.
INSERT INTO preview.tenants SELECT * FROM public.tenants;

-- Roles (orden idéntico, mismos auth.users en el mismo proyecto).
-- Incluye ya tenant_id, que casa con los UUID recién copiados.
-- Sin OVERRIDING: roles.id es GENERATED BY DEFAULT y acepta el id explícito.
INSERT INTO preview.roles SELECT * FROM public.roles;

-- Catálogos (orden idéntico, GENERATED ALWAYS)
INSERT INTO preview.conceptos_gasto      OVERRIDING SYSTEM VALUE SELECT * FROM public.conceptos_gasto;
INSERT INTO preview.subconceptos_gasto   OVERRIDING SYSTEM VALUE SELECT * FROM public.subconceptos_gasto;
INSERT INTO preview.conceptos_ingreso    OVERRIDING SYSTEM VALUE SELECT * FROM public.conceptos_ingreso;
INSERT INTO preview.subconceptos_ingreso OVERRIDING SYSTEM VALUE SELECT * FROM public.subconceptos_ingreso;

-- Animales (entidad unificada; orden idéntico entre schemas)
INSERT INTO preview.animales SELECT * FROM public.animales;

-- Respaldo previo a la unificación. Ningún código las lee; se copian solo
-- para que preview sea un clon fiel. Orden distinto → lista explícita.
INSERT INTO preview.toros_legacy (id, created_at, toro_id, nombre, origen,
  fecha_compra, numero_registro, madre_id, alta, fecha_nacimiento, estado, padre_id)
SELECT id, created_at, toro_id, nombre, origen,
  fecha_compra, numero_registro, madre_id, alta, fecha_nacimiento, estado, padre_id
FROM public.toros_legacy;

INSERT INTO preview.vacas_legacy (id, created_at, vaca_id, nombre, origen, estado,
  fecha_compra, numero_registro, madre_id, alta, fecha_nacimiento, padre_id, padre_pajilla_nombre)
SELECT id, created_at, vaca_id, nombre, origen, estado,
  fecha_compra, numero_registro, madre_id, alta, fecha_nacimiento, padre_id, padre_pajilla_nombre
FROM public.vacas_legacy;

-- Gastos (columnas en distinto orden, public tiene gaps por drops)
INSERT INTO preview.gastos (id, created_at, fecha, valor, observaciones, subconcepto_id,
  numero_factura, pagado, proveedor, tenant_id)
SELECT id, created_at, fecha, valor, observaciones, subconcepto_id,
  numero_factura, pagado, proveedor, tenant_id
FROM public.gastos;

-- Pagos (orden idéntico, GENERATED ALWAYS)
INSERT INTO preview.pagos OVERRIDING SYSTEM VALUE SELECT * FROM public.pagos;

-- Ingresos (columnas en distinto orden, public tiene gaps)
INSERT INTO preview.ingresos (id, created_at, fecha, valor, observaciones,
  subconcepto_id, source, tenant_id)
SELECT id, created_at, fecha, valor, observaciones,
  subconcepto_id, source, tenant_id
FROM public.ingresos;

-- Extracciones y precios (orden idéntico)
INSERT INTO preview.extracciones_leche SELECT * FROM public.extracciones_leche;
INSERT INTO preview.precios            SELECT * FROM public.precios;

-- Pajillas y eventos (orden idéntico; incluyen proveedor y pajilla_id)
INSERT INTO preview.pajillas       SELECT * FROM public.pajillas;
INSERT INTO preview.eventos_animal SELECT * FROM public.eventos_animal;

-- Cooperativa — no lleva tenant_id: es otro negocio, una sola cooperativa.
-- (columnas en distinto orden, public tiene gaps)
INSERT INTO preview.fincas_cooperativa (id, nombre, precio_litro, activa, created_at, metodo_pago)
SELECT id, nombre, precio_litro, activa, created_at, metodo_pago
FROM public.fincas_cooperativa;

INSERT INTO preview.rutas_cooperativa (id, nombre, created_at)
SELECT id, nombre, created_at
FROM public.rutas_cooperativa;

INSERT INTO preview.rutas_fincas SELECT * FROM public.rutas_fincas;

INSERT INTO preview.recolecciones (id, finca_id, fecha, litros, precio_litro, created_at)
SELECT id, finca_id, fecha, litros, precio_litro, created_at
FROM public.recolecciones;

-- Itinerarios (public.itinerarios usa plain integer PK sin sequence)
INSERT INTO preview.itinerarios (id, nombre, created_at)
SELECT id, nombre, created_at FROM public.itinerarios;

INSERT INTO preview.itinerarios_fincas (itinerario_id, finca_id, orden)
SELECT itinerario_id, finca_id, orden FROM public.itinerarios_fincas;

INSERT INTO preview.user_itinerarios (user_id, itinerario_id, created_at)
SELECT user_id, itinerario_id, created_at FROM public.user_itinerarios;

-- Pagos por finca (orden idéntico)
INSERT INTO preview.pagos_finca SELECT * FROM public.pagos_finca;


-- =============================================
-- 4. REACTIVAR FKs
-- =============================================
SET session_replication_role = 'origin';


-- =============================================
-- 5. SINCRONIZAR SECUENCIAS
--    Solo tablas con identity/sequence en preview.
--    `animales`, `eventos_animal`, `pajillas` y `tenants` usan UUID: no llevan.
-- =============================================
SELECT setval(pg_get_serial_sequence('preview.conceptos_gasto', 'id'),     COALESCE((SELECT MAX(id) FROM preview.conceptos_gasto), 1));
SELECT setval(pg_get_serial_sequence('preview.subconceptos_gasto', 'id'),  COALESCE((SELECT MAX(id) FROM preview.subconceptos_gasto), 1));
SELECT setval(pg_get_serial_sequence('preview.conceptos_ingreso', 'id'),   COALESCE((SELECT MAX(id) FROM preview.conceptos_ingreso), 1));
SELECT setval(pg_get_serial_sequence('preview.subconceptos_ingreso', 'id'),COALESCE((SELECT MAX(id) FROM preview.subconceptos_ingreso), 1));
SELECT setval(pg_get_serial_sequence('preview.gastos', 'id'),              COALESCE((SELECT MAX(id) FROM preview.gastos), 1));
SELECT setval(pg_get_serial_sequence('preview.pagos', 'id'),               COALESCE((SELECT MAX(id) FROM preview.pagos), 1));
SELECT setval(pg_get_serial_sequence('preview.ingresos', 'id'),            COALESCE((SELECT MAX(id) FROM preview.ingresos), 1));
SELECT setval(pg_get_serial_sequence('preview.extracciones_leche', 'id'),  COALESCE((SELECT MAX(id) FROM preview.extracciones_leche), 1));
SELECT setval(pg_get_serial_sequence('preview.precios', 'id'),             COALESCE((SELECT MAX(id) FROM preview.precios), 1));
SELECT setval(pg_get_serial_sequence('preview.fincas_cooperativa', 'id'),  COALESCE((SELECT MAX(id) FROM preview.fincas_cooperativa), 1));
SELECT setval(pg_get_serial_sequence('preview.rutas_cooperativa', 'id'),   COALESCE((SELECT MAX(id) FROM preview.rutas_cooperativa), 1));
SELECT setval(pg_get_serial_sequence('preview.recolecciones', 'id'),       COALESCE((SELECT MAX(id) FROM preview.recolecciones), 1));
SELECT setval(pg_get_serial_sequence('preview.pagos_finca', 'id'),         COALESCE((SELECT MAX(id) FROM preview.pagos_finca), 1));
SELECT setval(pg_get_serial_sequence('preview.roles', 'id'),               COALESCE((SELECT MAX(id) FROM preview.roles), 1));
SELECT setval(pg_get_serial_sequence('preview.itinerarios', 'id'),         COALESCE((SELECT MAX(id) FROM preview.itinerarios), 1));


-- =============================================
-- 6. COMPROBACIÓN
--    Debe devolver `true` en todas las filas.
-- =============================================
SELECT tabla, filas_public, filas_preview, filas_public = filas_preview AS ok
FROM (
  SELECT 'tenants' AS tabla,             (SELECT count(*) FROM public.tenants)             AS filas_public, (SELECT count(*) FROM preview.tenants)             AS filas_preview
  UNION ALL SELECT 'roles',              (SELECT count(*) FROM public.roles),              (SELECT count(*) FROM preview.roles)
  UNION ALL SELECT 'animales',           (SELECT count(*) FROM public.animales),           (SELECT count(*) FROM preview.animales)
  UNION ALL SELECT 'eventos_animal',     (SELECT count(*) FROM public.eventos_animal),     (SELECT count(*) FROM preview.eventos_animal)
  UNION ALL SELECT 'gastos',             (SELECT count(*) FROM public.gastos),             (SELECT count(*) FROM preview.gastos)
  UNION ALL SELECT 'pagos',              (SELECT count(*) FROM public.pagos),              (SELECT count(*) FROM preview.pagos)
  UNION ALL SELECT 'ingresos',           (SELECT count(*) FROM public.ingresos),           (SELECT count(*) FROM preview.ingresos)
  UNION ALL SELECT 'extracciones_leche', (SELECT count(*) FROM public.extracciones_leche), (SELECT count(*) FROM preview.extracciones_leche)
  UNION ALL SELECT 'precios',            (SELECT count(*) FROM public.precios),            (SELECT count(*) FROM preview.precios)
  UNION ALL SELECT 'pajillas',           (SELECT count(*) FROM public.pajillas),           (SELECT count(*) FROM preview.pajillas)
  UNION ALL SELECT 'recolecciones',      (SELECT count(*) FROM public.recolecciones),      (SELECT count(*) FROM preview.recolecciones)
  UNION ALL SELECT 'pagos_finca',        (SELECT count(*) FROM public.pagos_finca),        (SELECT count(*) FROM preview.pagos_finca)
) t ORDER BY tabla;

-- Y esta, 0 filas: ningún tenant_id huérfano.
SELECT 'animales' AS tabla, count(*) AS huerfanos FROM preview.animales a
  WHERE NOT EXISTS (SELECT 1 FROM preview.tenants t WHERE t.id = a.tenant_id)
UNION ALL
SELECT 'gastos', count(*) FROM preview.gastos g
  WHERE NOT EXISTS (SELECT 1 FROM preview.tenants t WHERE t.id = g.tenant_id)
UNION ALL
SELECT 'roles', count(*) FROM preview.roles r
  WHERE r.tenant_id IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM preview.tenants t WHERE t.id = r.tenant_id);
