-- =============================================
-- FINCA TOCA — Setup inicial del proyecto Supabase preview
--
-- Cómo usar:
--   1. Crear un nuevo proyecto en supabase.com (ej: "finca-toca-preview")
--   2. Ir a SQL Editor del nuevo proyecto
--   3. Pegar y ejecutar este script completo
--   4. Crear un usuario en Authentication → Users y añadir su rol (ver al final)
--
-- NOTA (2026-06-30): este script quedó desactualizado frente al schema "preview" real —
-- le faltan las tablas itinerarios/itinerarios_fincas/user_itinerarios/pagos_finca y usa
-- user_rutas/rutas_cooperativa en get_cooperativa_users() en vez de user_itinerarios/itinerarios.
-- Las políticas RLS de abajo sí están sincronizadas con lo aplicado en vivo a public y preview.
-- No usar este script para reconstruir un clon exacto de producción sin revisar ese gap antes.
-- =============================================


-- =============================================
-- 1. TIPOS ENUM
-- =============================================

CREATE TYPE public.vaca_origen AS ENUM ('finca', 'externa');
CREATE TYPE public.vaca_estado AS ENUM ('produccion', 'secado', 'pre_jardin', 'jardin', 'transicion');
CREATE TYPE public.rol AS ENUM ('admin', 'user', 'viewer', 'cooperativa_admin', 'cooperativa_user');


-- =============================================
-- 2. TABLAS
-- =============================================

-- Catálogos de gastos
CREATE TABLE public.conceptos_gasto (
  id   smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);

CREATE TABLE public.subconceptos_gasto (
  id          smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  concepto_id smallint NOT NULL REFERENCES public.conceptos_gasto(id),
  nombre      text     NOT NULL,
  UNIQUE (concepto_id, nombre)
);

-- Catálogos de ingresos
CREATE TABLE public.conceptos_ingreso (
  id     smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre text     NOT NULL UNIQUE
);

CREATE TABLE public.subconceptos_ingreso (
  id          smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  concepto_id smallint NOT NULL REFERENCES public.conceptos_ingreso(id),
  nombre      text     NOT NULL,
  UNIQUE (concepto_id, nombre)
);

-- Toros (sin FK a vacas todavía — dependencia circular)
CREATE TABLE public.toros (
  id               uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       timestamptz  DEFAULT now(),
  toro_id          integer      NOT NULL,
  nombre           varchar      NOT NULL,
  origen           public.vaca_origen,
  estado           text         CHECK (estado = ANY (ARRAY['jardin'::text, 'reproductor'::text])),
  fecha_compra     date,
  fecha_nacimiento date,
  numero_registro  text,
  madre_id         uuid,                              -- FK a vacas añadida más abajo
  padre_id         uuid         REFERENCES public.toros(id),
  alta             boolean      NOT NULL DEFAULT true
);

-- Vacas (sin FK a toros todavía — dependencia circular)
CREATE TABLE public.vacas (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at          timestamptz  DEFAULT now(),
  vaca_id             integer      NOT NULL UNIQUE,
  nombre              varchar      NOT NULL,
  origen              public.vaca_origen,
  estado              public.vaca_estado,
  fecha_compra        date,
  fecha_nacimiento    date,
  numero_registro     text,
  madre_id            uuid         REFERENCES public.vacas(id),
  padre_id            uuid,                           -- FK a toros añadida más abajo
  padre_pajilla_nombre text,
  alta                boolean      NOT NULL DEFAULT true
);

-- Resolver la dependencia circular toros ↔ vacas
ALTER TABLE public.toros
  ADD CONSTRAINT toros_madre_id_fkey FOREIGN KEY (madre_id) REFERENCES public.vacas(id);
ALTER TABLE public.vacas
  ADD CONSTRAINT vacas_padre_id_fkey FOREIGN KEY (padre_id) REFERENCES public.toros(id);

-- Gastos
CREATE TABLE public.gastos (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamptz NOT NULL DEFAULT now(),
  fecha          date        NOT NULL,
  valor          bigint      NOT NULL,
  subconcepto_id smallint    REFERENCES public.subconceptos_gasto(id),
  proveedor      text,
  numero_factura text,
  observaciones  varchar,
  pagado         boolean     NOT NULL DEFAULT false
);

-- Pagos (1-a-1 con gastos)
CREATE TABLE public.pagos (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  gasto_id     bigint NOT NULL UNIQUE REFERENCES public.gastos(id),
  forma_pago   text   NOT NULL CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'transferencia'::text])),
  tipo_cuenta  text,
  banco        text,
  numero_cuenta text
);

-- Ingresos
CREATE TABLE public.ingresos (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamptz NOT NULL DEFAULT now(),
  fecha          date        NOT NULL,
  valor          bigint      NOT NULL,
  subconcepto_id smallint    NOT NULL REFERENCES public.subconceptos_ingreso(id),
  observaciones  varchar,
  source         text
);

-- Extracciones de leche
CREATE TABLE public.extracciones_leche (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          timestamptz NOT NULL DEFAULT now(),
  fecha               date        NOT NULL,
  litros              real        NOT NULL,
  vacas_en_produccion integer
);

-- Precios
CREATE TABLE public.precios (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  valor      integer     NOT NULL,
  tipo       text        NOT NULL DEFAULT 'leche'
);

-- Inventario de pajillas (semen)
CREATE TABLE public.pajillas (
  id                 uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at         timestamptz NOT NULL DEFAULT now(),
  toro_nombre        text    NOT NULL,
  toro_ref_id        text    NOT NULL,
  fecha_compra       date    NOT NULL,
  cantidad           integer NOT NULL CHECK (cantidad > 0),
  cantidad_disponible integer NOT NULL CHECK (cantidad_disponible >= 0),
  observaciones      text
);

-- Eventos por animal
CREATE TABLE public.eventos_animal (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  animal_id   uuid NOT NULL,
  animal_tipo text NOT NULL CHECK (animal_tipo = ANY (ARRAY['vaca'::text, 'toro'::text])),
  tipo_evento text NOT NULL CHECK (tipo_evento = ANY (ARRAY[
    'vacunacion'::text, 'vitaminacion'::text, 'medicamento'::text,
    'enfermedad'::text, 'celo'::text, 'inseminacion'::text,
    'palpacion'::text, 'confirmacion_prenez'::text, 'parto'::text, 'observacion'::text
  ])),
  fecha       date NOT NULL,
  descripcion text,
  responsable text
);

-- Cooperativa
CREATE TABLE public.fincas_cooperativa (
  id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  nombre      text        NOT NULL,
  precio_litro numeric    NOT NULL DEFAULT 0,
  activa      boolean     NOT NULL DEFAULT true,
  metodo_pago text        NOT NULL DEFAULT 'conductor'
                CHECK (metodo_pago IN ('conductor','punto_venta','gerente'))
);

CREATE TABLE public.rutas_cooperativa (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nombre     text        NOT NULL
);

CREATE TABLE public.rutas_fincas (
  ruta_id  integer NOT NULL REFERENCES public.rutas_cooperativa(id),
  finca_id integer NOT NULL UNIQUE REFERENCES public.fincas_cooperativa(id),
  orden    integer NOT NULL DEFAULT 0,
  PRIMARY KEY (ruta_id, finca_id)
);

CREATE TABLE public.recolecciones (
  id           integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  finca_id     integer     NOT NULL REFERENCES public.fincas_cooperativa(id),
  fecha        date        NOT NULL,
  litros       numeric     NOT NULL,
  precio_litro numeric     NOT NULL,
  UNIQUE (finca_id, fecha)
);

CREATE TABLE public.pagos_finca (
  id            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  finca_id      integer     NOT NULL REFERENCES public.fincas_cooperativa(id),
  itinerario_id integer     REFERENCES public.itinerarios(id),
  fecha_inicio  date        NOT NULL,
  fecha_fin     date        NOT NULL,
  litros        numeric     NOT NULL DEFAULT 0,
  estado        text        NOT NULL DEFAULT 'pendiente'
                  CHECK (estado IN ('pendiente','pagado','punto_venta','devuelto')),
  responsable   text        NOT NULL DEFAULT 'conductor'
                  CHECK (responsable IN ('conductor','punto_venta','gerente')),
  fecha_marcado timestamptz,
  activado_por  uuid        REFERENCES auth.users(id),
  marcado_por   uuid        REFERENCES auth.users(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX pagos_finca_finca_id_idx ON public.pagos_finca(finca_id);
CREATE INDEX pagos_finca_itinerario_id_idx ON public.pagos_finca(itinerario_id);
CREATE INDEX pagos_finca_estado_idx ON public.pagos_finca(estado);

CREATE TABLE public.user_rutas (
  user_id    uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  ruta_id    integer     NOT NULL REFERENCES public.rutas_cooperativa(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Roles de usuarios
CREATE TABLE public.roles (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id),
  rol        public.rol  NOT NULL
);


-- =============================================
-- 3. ÍNDICES
-- =============================================

CREATE INDEX idx_eventos_animal_id            ON public.eventos_animal     USING btree (animal_id);
CREATE INDEX idx_extracciones_leche_fecha     ON public.extracciones_leche USING btree (fecha);
CREATE INDEX idx_gastos_fecha                 ON public.gastos             USING btree (fecha);
CREATE INDEX idx_gastos_subconcepto_id        ON public.gastos             USING btree (subconcepto_id);
CREATE INDEX idx_ingresos_fecha               ON public.ingresos           USING btree (fecha);
CREATE INDEX idx_ingresos_source              ON public.ingresos           USING btree (source);
CREATE INDEX idx_ingresos_subconcepto_id      ON public.ingresos           USING btree (subconcepto_id);
CREATE INDEX idx_pagos_gasto_id               ON public.pagos              USING btree (gasto_id);
CREATE INDEX idx_recolecciones_fecha          ON public.recolecciones      USING btree (fecha);
CREATE INDEX idx_recolecciones_finca_id       ON public.recolecciones      USING btree (finca_id);
CREATE INDEX idx_vacas_madre_id               ON public.vacas              USING btree (madre_id);
CREATE INDEX subconceptos_gasto_concepto_id_idx    ON public.subconceptos_gasto   USING btree (concepto_id);
CREATE INDEX subconceptos_ingreso_concepto_id_idx  ON public.subconceptos_ingreso USING btree (concepto_id);


-- =============================================
-- 4. ROW LEVEL SECURITY
-- =============================================

ALTER TABLE public.conceptos_gasto      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subconceptos_gasto   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conceptos_ingreso    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subconceptos_ingreso ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingresos             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.extracciones_leche   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.precios              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pajillas             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toros                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacas                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_animal       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fincas_cooperativa   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas_cooperativa    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas_fincas         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recolecciones        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_rutas           ENABLE ROW LEVEL SECURITY;

-- NOTA: estas políticas validan roles.rol (no solo "authenticated"). Mirrors la migración
-- "enforce_app_roles_in_rls" aplicada en vivo a public/preview — ver requireRole() de cada
-- features/*/actions para la matriz de roles exacta.

-- conceptos_gasto / subconceptos_gasto / conceptos_ingreso / subconceptos_ingreso
-- (sin create/update/delete en la app: escritura restringida a admin)
CREATE POLICY "conceptos_gasto_select" ON public.conceptos_gasto FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "conceptos_gasto_write" ON public.conceptos_gasto FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));

CREATE POLICY "subconceptos_gasto_select" ON public.subconceptos_gasto FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "subconceptos_gasto_write" ON public.subconceptos_gasto FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));

CREATE POLICY "conceptos_ingreso_select" ON public.conceptos_ingreso FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "conceptos_ingreso_write" ON public.conceptos_ingreso FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));

CREATE POLICY "subconceptos_ingreso_select" ON public.subconceptos_ingreso FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "subconceptos_ingreso_write" ON public.subconceptos_ingreso FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));

-- gastos / pagos (detalle 1-a-1) / ingresos / extracciones_leche / pajillas: admin+user escriben, viewer solo lee
CREATE POLICY "gastos_select" ON public.gastos FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "gastos_insert" ON public.gastos FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "gastos_update" ON public.gastos FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "gastos_delete" ON public.gastos FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

CREATE POLICY "pagos_select" ON public.pagos FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "pagos_insert" ON public.pagos FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "pagos_update" ON public.pagos FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "pagos_delete" ON public.pagos FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

CREATE POLICY "ingresos_select" ON public.ingresos FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "ingresos_insert" ON public.ingresos FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "ingresos_update" ON public.ingresos FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "ingresos_delete" ON public.ingresos FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

CREATE POLICY "extracciones_leche_select" ON public.extracciones_leche FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "extracciones_leche_insert" ON public.extracciones_leche FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "extracciones_leche_update" ON public.extracciones_leche FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "extracciones_leche_delete" ON public.extracciones_leche FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

-- precios: solo admin escribe
CREATE POLICY "precios_select" ON public.precios FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "precios_insert" ON public.precios FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));
CREATE POLICY "precios_update" ON public.precios FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));
CREATE POLICY "precios_delete" ON public.precios FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = 'admin'::public.rol));

CREATE POLICY "pajillas_select" ON public.pajillas FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "pajillas_insert" ON public.pajillas FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "pajillas_update" ON public.pajillas FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "pajillas_delete" ON public.pajillas FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

-- toros / vacas
CREATE POLICY "toros_select" ON public.toros FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "toros_insert" ON public.toros FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "toros_update" ON public.toros FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "toros_delete" ON public.toros FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

CREATE POLICY "vacas_select" ON public.vacas FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "vacas_insert" ON public.vacas FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "vacas_update" ON public.vacas FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "vacas_delete" ON public.vacas FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

-- eventos_animal (incluye UPDATE, ausente en el script original — updateEventoAnimal fallaba en silencio)
CREATE POLICY "eventos_animal_select" ON public.eventos_animal FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol,'viewer'::public.rol])));
CREATE POLICY "eventos_animal_insert" ON public.eventos_animal FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));
CREATE POLICY "eventos_animal_update" ON public.eventos_animal FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'user'::public.rol])));

-- fincas_cooperativa / rutas_cooperativa / rutas_fincas: cooperativa_admin (+admin) escriben, cooperativa_user solo lee
CREATE POLICY "cooperativa_read_fincas" ON public.fincas_cooperativa FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "cooperativa_admin_insert_fincas" ON public.fincas_cooperativa FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));
CREATE POLICY "cooperativa_admin_update_fincas" ON public.fincas_cooperativa FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));
CREATE POLICY "cooperativa_admin_delete_fincas" ON public.fincas_cooperativa FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));

CREATE POLICY "cooperativa_read_rutas" ON public.rutas_cooperativa FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "cooperativa_admin_mutate_rutas" ON public.rutas_cooperativa FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));

CREATE POLICY "cooperativa_read_rutas_fincas" ON public.rutas_fincas FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "cooperativa_admin_mutate_rutas_fincas" ON public.rutas_fincas FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));

-- recolecciones: admin/cooperativa_admin/cooperativa_user insertan y actualizan; solo admin/cooperativa_admin borran
CREATE POLICY "recolecciones_select" ON public.recolecciones FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "recolecciones_insert" ON public.recolecciones FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "recolecciones_update" ON public.recolecciones FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])))
  WITH CHECK (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol,'cooperativa_user'::public.rol])));
CREATE POLICY "recolecciones_delete" ON public.recolecciones FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM public.roles WHERE roles.user_id = auth.uid() AND roles.rol = ANY (ARRAY['admin'::public.rol,'cooperativa_admin'::public.rol])));

-- roles (cada usuario solo ve su propio rol)
CREATE POLICY "Users can view own role" ON public.roles FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- user_rutas
CREATE POLICY "Authenticated users can select user_rutas"
  ON public.user_rutas FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert user_rutas"
  ON public.user_rutas FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update user_rutas"
  ON public.user_rutas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated users can delete user_rutas"
  ON public.user_rutas FOR DELETE TO authenticated USING (true);

-- =============================================
-- FUNCIONES
-- =============================================

CREATE OR REPLACE FUNCTION public.get_cooperativa_users()
RETURNS TABLE (
  user_id     uuid,
  email       text,
  ruta_id     integer,
  ruta_nombre text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  RETURN QUERY
  SELECT
    r.user_id,
    u.email::text,
    ur.ruta_id,
    rc.nombre::text AS ruta_nombre
  FROM public.roles r
  JOIN auth.users u ON u.id = r.user_id
  LEFT JOIN public.user_rutas ur ON ur.user_id = r.user_id
  LEFT JOIN public.rutas_cooperativa rc ON rc.id = ur.ruta_id
  WHERE r.rol = 'cooperativa_user'
  ORDER BY u.email;
END;
$$;

-- Solo "authenticated" — nunca "anon". Postgres también concede EXECUTE a PUBLIC por
-- defecto al crear la función; hay que revocarlo explícitamente o anon sigue teniendo acceso.
GRANT EXECUTE ON FUNCTION public.get_cooperativa_users() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_cooperativa_users() FROM PUBLIC;

-- =============================================
-- 5. DATOS INICIALES (catálogos)
-- =============================================

-- Conceptos de gasto
INSERT INTO public.conceptos_gasto (id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (13, 'Alimentación animal'),
  (14, 'Mano de obra'),
  (15, 'Operación y mantenimiento'),
  (16, 'Praderas y forrajes'),
  (17, 'Sanidad y reproducción');
SELECT setval(pg_get_serial_sequence('public.conceptos_gasto', 'id'), (SELECT MAX(id) FROM public.conceptos_gasto));

-- Subconceptos de gasto
INSERT INTO public.subconceptos_gasto (id, concepto_id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (30, 13, 'Afrecho'),
  (31, 13, 'Concentrado'),
  (32, 13, 'Heno'),
  (33, 13, 'Papa'),
  (34, 13, 'Sal'),
  (35, 13, 'Silo'),
  (36, 13, 'Otros'),
  (37, 14, 'Bonificaciones'),
  (38, 14, 'Jornales'),
  (39, 14, 'Salarios'),
  (40, 14, 'Otros'),
  (41, 15, 'Arriendos'),
  (42, 15, 'Maquinaria nueva'),
  (43, 15, 'Repuestos / mantenimiento'),
  (44, 15, 'Insumos de aseo'),
  (45, 15, 'ACPM'),
  (46, 15, 'Gasolina'),
  (47, 15, 'Transporte'),
  (48, 15, 'Lazos'),
  (49, 15, 'Plaquetas'),
  (50, 15, 'Otros'),
  (51, 16, 'Abono'),
  (52, 16, 'Fertilizante'),
  (53, 16, 'Fungicidas'),
  (54, 16, 'Pasto'),
  (55, 16, 'Potreros'),
  (56, 16, 'Semilla'),
  (57, 16, 'Otros'),
  (58, 17, 'Inseminación'),
  (59, 17, 'Jeringas'),
  (60, 17, 'Medicamentos'),
  (61, 17, 'Pajillas'),
  (62, 17, 'Vacunación'),
  (63, 17, 'Veterinario'),
  (64, 17, 'Otros');
SELECT setval(pg_get_serial_sequence('public.subconceptos_gasto', 'id'), (SELECT MAX(id) FROM public.subconceptos_gasto));

-- Conceptos de ingreso
INSERT INTO public.conceptos_ingreso (id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (1, 'Leche'),
  (2, 'Venta terneros'),
  (3, 'Venta vacas'),
  (4, 'Venta toros');
SELECT setval(pg_get_serial_sequence('public.conceptos_ingreso', 'id'), (SELECT MAX(id) FROM public.conceptos_ingreso));

-- Subconceptos de ingreso
INSERT INTO public.subconceptos_ingreso (id, concepto_id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (1, 1, 'General'),
  (2, 2, 'General'),
  (3, 3, 'General'),
  (4, 4, 'General'),
  (5, 1, 'Leche');
SELECT setval(pg_get_serial_sequence('public.subconceptos_ingreso', 'id'), (SELECT MAX(id) FROM public.subconceptos_ingreso));


-- =============================================
-- 6. USUARIO DE PRUEBA
-- =============================================
-- Después de crear el usuario en Authentication → Users, ejecuta esto
-- reemplazando <USER_UUID> por el UUID del usuario creado:
--
-- INSERT INTO public.roles (user_id, rol) VALUES ('<USER_UUID>', 'admin');
