-- =============================================
-- FINCA TOCA — Setup inicial del proyecto Supabase preview
--
-- Cómo usar:
--   1. Crear un nuevo proyecto en supabase.com (ej: "finca-toca-preview")
--   2. Ir a SQL Editor del nuevo proyecto
--   3. Pegar y ejecutar este script completo
--   4. Crear un usuario en Authentication → Users y añadir su rol (ver al final)
-- =============================================


-- =============================================
-- 1. TIPOS ENUM
-- =============================================

CREATE TYPE public.vaca_origen AS ENUM ('finca', 'externa');
CREATE TYPE public.vaca_estado AS ENUM ('produccion', 'secado', 'pre_jardin', 'jardin', 'transicion');


-- =============================================
-- 2. TABLAS
-- =============================================

-- Catálogos de gastos
CREATE TABLE public.conceptos_gasto (
  id   smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);

CREATE TABLE public.subconceptos_gasto (
  id          smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  concepto_id smallint NOT NULL REFERENCES public.conceptos_gasto(id),
  nombre      text     NOT NULL,
  UNIQUE (concepto_id, nombre)
);

-- Catálogos de ingresos
CREATE TABLE public.conceptos_ingreso (
  id     smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre text     NOT NULL UNIQUE
);

CREATE TABLE public.subconceptos_ingreso (
  id          smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  concepto_id smallint NOT NULL REFERENCES public.conceptos_ingreso(id),
  nombre      text     NOT NULL,
  UNIQUE (concepto_id, nombre)
);

-- Toros (sin FK a vacas todavía — dependencia circular)
CREATE TABLE public.toros (
  id               uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       timestamptz  DEFAULT now(),
  toro_id          integer      NOT NULL,
  nombre           varchar      NOT NULL,
  origen           public.vaca_origen,
  estado           text         CHECK (estado = ANY (ARRAY['jardin'::text, 'reproductor'::text])),
  fecha_compra     date,
  fecha_nacimiento date,
  numero_registro  text,
  madre_id         uuid,                              -- FK a vacas añadida más abajo
  padre_id         uuid         REFERENCES public.toros(id),
  alta             boolean      NOT NULL DEFAULT true
);

-- Vacas (sin FK a toros todavía — dependencia circular)
CREATE TABLE public.vacas (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at          timestamptz  DEFAULT now(),
  vaca_id             integer      NOT NULL UNIQUE,
  nombre              varchar      NOT NULL,
  origen              public.vaca_origen,
  estado              public.vaca_estado,
  fecha_compra        date,
  fecha_nacimiento    date,
  numero_registro     text,
  madre_id            uuid         REFERENCES public.vacas(id),
  padre_id            uuid,                           -- FK a toros añadida más abajo
  padre_pajilla_nombre text,
  alta                boolean      NOT NULL DEFAULT true
);

-- Resolver la dependencia circular toros ↔ vacas
ALTER TABLE public.toros
  ADD CONSTRAINT toros_madre_id_fkey FOREIGN KEY (madre_id) REFERENCES public.vacas(id);
ALTER TABLE public.vacas
  ADD CONSTRAINT vacas_padre_id_fkey FOREIGN KEY (padre_id) REFERENCES public.toros(id);

-- Gastos
CREATE TABLE public.gastos (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamptz NOT NULL DEFAULT now(),
  fecha          date        NOT NULL,
  valor          bigint      NOT NULL,
  subconcepto_id smallint    REFERENCES public.subconceptos_gasto(id),
  proveedor      text,
  numero_factura text,
  observaciones  varchar,
  pagado         boolean     NOT NULL DEFAULT false
);

-- Pagos (1-a-1 con gastos)
CREATE TABLE public.pagos (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  gasto_id     bigint NOT NULL UNIQUE REFERENCES public.gastos(id),
  forma_pago   text   NOT NULL CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'transferencia'::text])),
  tipo_cuenta  text,
  banco        text,
  numero_cuenta text
);

-- Ingresos
CREATE TABLE public.ingresos (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamptz NOT NULL DEFAULT now(),
  fecha          date        NOT NULL,
  valor          bigint      NOT NULL,
  subconcepto_id smallint    NOT NULL REFERENCES public.subconceptos_ingreso(id),
  observaciones  varchar,
  source         text
);

-- Extracciones de leche
CREATE TABLE public.extracciones_leche (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          timestamptz NOT NULL DEFAULT now(),
  fecha               date        NOT NULL,
  litros              real        NOT NULL,
  vacas_en_produccion integer
);

-- Precios
CREATE TABLE public.precios (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  valor      integer     NOT NULL,
  tipo       text        NOT NULL DEFAULT 'leche'
);

-- Inventario de pajillas (semen)
CREATE TABLE public.pajillas (
  id                 uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at         timestamptz NOT NULL DEFAULT now(),
  toro_nombre        text    NOT NULL,
  toro_ref_id        text    NOT NULL,
  fecha_compra       date    NOT NULL,
  cantidad           integer NOT NULL CHECK (cantidad > 0),
  cantidad_disponible integer NOT NULL CHECK (cantidad_disponible >= 0),
  observaciones      text
);

-- Eventos por animal
CREATE TABLE public.eventos_animal (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  animal_id   uuid NOT NULL,
  animal_tipo text NOT NULL CHECK (animal_tipo = ANY (ARRAY['vaca'::text, 'toro'::text])),
  tipo_evento text NOT NULL CHECK (tipo_evento = ANY (ARRAY[
    'vacunacion'::text, 'vitaminacion'::text, 'medicamento'::text,
    'enfermedad'::text, 'celo'::text, 'inseminacion'::text,
    'palpacion'::text, 'confirmacion_prenez'::text, 'parto'::text, 'observacion'::text
  ])),
  fecha       date NOT NULL,
  descripcion text,
  responsable text
);

-- Cooperativa
CREATE TABLE public.fincas_cooperativa (
  id          integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  nombre      text        NOT NULL,
  precio_litro numeric    NOT NULL DEFAULT 0,
  activa      boolean     NOT NULL DEFAULT true
);

CREATE TABLE public.rutas_cooperativa (
  id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nombre     text        NOT NULL
);

CREATE TABLE public.rutas_fincas (
  ruta_id  integer NOT NULL REFERENCES public.rutas_cooperativa(id),
  finca_id integer NOT NULL UNIQUE REFERENCES public.fincas_cooperativa(id),
  PRIMARY KEY (ruta_id, finca_id)
);

CREATE TABLE public.recolecciones (
  id           integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  finca_id     integer     NOT NULL REFERENCES public.fincas_cooperativa(id),
  fecha        date        NOT NULL,
  litros       numeric     NOT NULL,
  precio_litro numeric     NOT NULL,
  UNIQUE (finca_id, fecha)
);

-- Roles de usuarios
CREATE TABLE public.roles (
  id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id),
  rol        varchar     NOT NULL
);


-- =============================================
-- 3. ÍNDICES
-- =============================================

CREATE INDEX idx_eventos_animal_id            ON public.eventos_animal     USING btree (animal_id);
CREATE INDEX idx_extracciones_leche_fecha     ON public.extracciones_leche USING btree (fecha);
CREATE INDEX idx_gastos_fecha                 ON public.gastos             USING btree (fecha);
CREATE INDEX idx_gastos_subconcepto_id        ON public.gastos             USING btree (subconcepto_id);
CREATE INDEX idx_ingresos_fecha               ON public.ingresos           USING btree (fecha);
CREATE INDEX idx_ingresos_source              ON public.ingresos           USING btree (source);
CREATE INDEX idx_ingresos_subconcepto_id      ON public.ingresos           USING btree (subconcepto_id);
CREATE INDEX idx_pagos_gasto_id               ON public.pagos              USING btree (gasto_id);
CREATE INDEX idx_recolecciones_fecha          ON public.recolecciones      USING btree (fecha);
CREATE INDEX idx_recolecciones_finca_id       ON public.recolecciones      USING btree (finca_id);
CREATE INDEX idx_vacas_madre_id               ON public.vacas              USING btree (madre_id);
CREATE INDEX subconceptos_gasto_concepto_id_idx    ON public.subconceptos_gasto   USING btree (concepto_id);
CREATE INDEX subconceptos_ingreso_concepto_id_idx  ON public.subconceptos_ingreso USING btree (concepto_id);


-- =============================================
-- 4. ROW LEVEL SECURITY
-- =============================================

ALTER TABLE public.conceptos_gasto      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subconceptos_gasto   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conceptos_ingreso    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subconceptos_ingreso ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingresos             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.extracciones_leche   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.precios              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pajillas             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toros                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacas                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_animal       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fincas_cooperativa   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas_cooperativa    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas_fincas         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recolecciones        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles                ENABLE ROW LEVEL SECURITY;

-- conceptos_gasto
CREATE POLICY "Authenticated users can select conceptos_gasto" ON public.conceptos_gasto FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert conceptos_gasto" ON public.conceptos_gasto FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update conceptos_gasto" ON public.conceptos_gasto FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete conceptos_gasto" ON public.conceptos_gasto FOR DELETE TO authenticated USING (true);

-- subconceptos_gasto
CREATE POLICY "Authenticated users can select subconceptos_gasto" ON public.subconceptos_gasto FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert subconceptos_gasto" ON public.subconceptos_gasto FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update subconceptos_gasto" ON public.subconceptos_gasto FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete subconceptos_gasto" ON public.subconceptos_gasto FOR DELETE TO authenticated USING (true);

-- conceptos_ingreso
CREATE POLICY "Authenticated users can select conceptos_ingreso" ON public.conceptos_ingreso FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert conceptos_ingreso" ON public.conceptos_ingreso FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update conceptos_ingreso" ON public.conceptos_ingreso FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete conceptos_ingreso" ON public.conceptos_ingreso FOR DELETE TO authenticated USING (true);

-- subconceptos_ingreso
CREATE POLICY "Authenticated users can select subconceptos_ingreso" ON public.subconceptos_ingreso FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert subconceptos_ingreso" ON public.subconceptos_ingreso FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update subconceptos_ingreso" ON public.subconceptos_ingreso FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete subconceptos_ingreso" ON public.subconceptos_ingreso FOR DELETE TO authenticated USING (true);

-- gastos
CREATE POLICY "Authenticated users can view gastos"            ON public.gastos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"     ON public.gastos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "allow_authenticated_update_gastos"              ON public.gastos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated deletes"                    ON public.gastos FOR DELETE TO authenticated USING (true);

-- pagos
CREATE POLICY "Enable read for authenticated"   ON public.pagos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated" ON public.pagos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated" ON public.pagos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated" ON public.pagos FOR DELETE TO authenticated USING (true);

-- ingresos
CREATE POLICY "Authenticated users can view ingresos"         ON public.ingresos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"    ON public.ingresos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "allow_authenticated_update_ingresos"           ON public.ingresos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated deletes"                   ON public.ingresos FOR DELETE TO authenticated USING (true);

-- extracciones_leche
CREATE POLICY "Authenticated users can view extracciones_leche"     ON public.extracciones_leche FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"          ON public.extracciones_leche FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "allow_authenticated_update_extracciones_leche"       ON public.extracciones_leche FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated deletes"                         ON public.extracciones_leche FOR DELETE TO authenticated USING (true);

-- precios
CREATE POLICY "authenticated users can do all on precios" ON public.precios FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- pajillas
CREATE POLICY "Enable read access for authenticated users" ON public.pajillas FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users"      ON public.pajillas FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users"      ON public.pajillas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users"      ON public.pajillas FOR DELETE TO authenticated USING (true);

-- toros
CREATE POLICY "Enable read access for authenticated users only" ON public.toros FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"      ON public.toros FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only"      ON public.toros FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users only"      ON public.toros FOR DELETE TO authenticated USING (true);

-- vacas
CREATE POLICY "Enable read access for all users"           ON public.vacas FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.vacas FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON public.vacas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users only" ON public.vacas FOR DELETE TO authenticated USING (true);

-- eventos_animal
CREATE POLICY "Authenticated users can read eventos"  ON public.eventos_animal FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert eventos" ON public.eventos_animal FOR INSERT TO authenticated WITH CHECK (true);

-- fincas_cooperativa
CREATE POLICY "Authenticated users can select fincas_cooperativa" ON public.fincas_cooperativa FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert fincas_cooperativa" ON public.fincas_cooperativa FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update fincas_cooperativa" ON public.fincas_cooperativa FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete fincas_cooperativa" ON public.fincas_cooperativa FOR DELETE TO authenticated USING (true);

-- rutas_cooperativa
CREATE POLICY "Authenticated users can select rutas_cooperativa" ON public.rutas_cooperativa FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert rutas_cooperativa" ON public.rutas_cooperativa FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update rutas_cooperativa" ON public.rutas_cooperativa FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete rutas_cooperativa" ON public.rutas_cooperativa FOR DELETE TO authenticated USING (true);

-- rutas_fincas
CREATE POLICY "Authenticated users can select rutas_fincas" ON public.rutas_fincas FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert rutas_fincas" ON public.rutas_fincas FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update rutas_fincas" ON public.rutas_fincas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete rutas_fincas" ON public.rutas_fincas FOR DELETE TO authenticated USING (true);

-- recolecciones
CREATE POLICY "Authenticated users can select recolecciones" ON public.recolecciones FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert recolecciones" ON public.recolecciones FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can update recolecciones" ON public.recolecciones FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can delete recolecciones" ON public.recolecciones FOR DELETE TO authenticated USING (true);

-- roles (cada usuario solo ve su propio rol)
CREATE POLICY "Users can view own role" ON public.roles FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);


-- =============================================
-- 5. DATOS INICIALES (catálogos)
-- =============================================

-- Conceptos de gasto
INSERT INTO public.conceptos_gasto (id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (13, 'Alimentación animal'),
  (14, 'Mano de obra'),
  (15, 'Operación y mantenimiento'),
  (16, 'Praderas y forrajes'),
  (17, 'Sanidad y reproducción');
SELECT setval(pg_get_serial_sequence('public.conceptos_gasto', 'id'), (SELECT MAX(id) FROM public.conceptos_gasto));

-- Subconceptos de gasto
INSERT INTO public.subconceptos_gasto (id, concepto_id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (30, 13, 'Afrecho'),
  (31, 13, 'Concentrado'),
  (32, 13, 'Heno'),
  (33, 13, 'Papa'),
  (34, 13, 'Sal'),
  (35, 13, 'Silo'),
  (36, 13, 'Otros'),
  (37, 14, 'Bonificaciones'),
  (38, 14, 'Jornales'),
  (39, 14, 'Salarios'),
  (40, 14, 'Otros'),
  (41, 15, 'Arriendos'),
  (42, 15, 'Maquinaria nueva'),
  (43, 15, 'Repuestos / mantenimiento'),
  (44, 15, 'Insumos de aseo'),
  (45, 15, 'ACPM'),
  (46, 15, 'Gasolina'),
  (47, 15, 'Transporte'),
  (48, 15, 'Lazos'),
  (49, 15, 'Plaquetas'),
  (50, 15, 'Otros'),
  (51, 16, 'Abono'),
  (52, 16, 'Fertilizante'),
  (53, 16, 'Fungicidas'),
  (54, 16, 'Pasto'),
  (55, 16, 'Potreros'),
  (56, 16, 'Semilla'),
  (57, 16, 'Otros'),
  (58, 17, 'Inseminación'),
  (59, 17, 'Jeringas'),
  (60, 17, 'Medicamentos'),
  (61, 17, 'Pajillas'),
  (62, 17, 'Vacunación'),
  (63, 17, 'Veterinario'),
  (64, 17, 'Otros');
SELECT setval(pg_get_serial_sequence('public.subconceptos_gasto', 'id'), (SELECT MAX(id) FROM public.subconceptos_gasto));

-- Conceptos de ingreso
INSERT INTO public.conceptos_ingreso (id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (1, 'Leche'),
  (2, 'Venta terneros'),
  (3, 'Venta vacas'),
  (4, 'Venta toros');
SELECT setval(pg_get_serial_sequence('public.conceptos_ingreso', 'id'), (SELECT MAX(id) FROM public.conceptos_ingreso));

-- Subconceptos de ingreso
INSERT INTO public.subconceptos_ingreso (id, concepto_id, nombre) OVERRIDING SYSTEM VALUE VALUES
  (1, 1, 'General'),
  (2, 2, 'General'),
  (3, 3, 'General'),
  (4, 4, 'General'),
  (5, 1, 'Leche');
SELECT setval(pg_get_serial_sequence('public.subconceptos_ingreso', 'id'), (SELECT MAX(id) FROM public.subconceptos_ingreso));


-- =============================================
-- 6. USUARIO DE PRUEBA
-- =============================================
-- Después de crear el usuario en Authentication → Users, ejecuta esto
-- reemplazando <USER_UUID> por el UUID del usuario creado:
--
-- INSERT INTO public.roles (user_id, rol) VALUES ('<USER_UUID>', 'admin');
